openapi: 3.0.3
info:
  description: Stub to use for codegen of parameters for a hub client
  version: ''
  title: '@auditmation/hub-client-codegen'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
components:
  schemas:
    Parameters:
      type: object
      properties:
        organizationId:
          type: string
          description: The organization ID to collect data for. If not provided, defaults to the organization of the authenticated user.
          example: '12345'
