/**
 * Temporary local stand-in for @zerobias-org/schema-nist-cmvp-ts.
 *
 * The real -ts twin is generated by the zb.schema Gradle plugin's
 * schema-ts-generator, which only runs as a post-load action of
 * dataloaderExec (needs a live Neon branch — blocked in this sandbox by
 * the same missing-credentials gap documented throughout
 * CMVP_Connector_STATUS.md). This mirrors
 * schema/package/nist/cmvp/classes/CmvpCertificate.yml and its
 * fields/cmvpCertificate.*.yml field-for-field. Delete this file and
 * import from the real published -ts package once schema's gate can
 * actually run (CI, with real Neon credentials).
 */
export interface CmvpCertificate {
  id: string;
  name: string;
  certificateNumber: string;
  moduleName: string;
  standard: string;
  status: string;
  sunsetDate?: string;
  overallLevel: number;
  moduleType: string;
  embodiment?: string;
  caveatText: string;
  overview?: string;
  securityLevelExceptions?: string;
  vendorName: string;
  vendorAddress?: string;
  vendorContact?: string;
  validationType?: string;
  validationLab?: string;
  validationDate?: string;
  securityPolicyUrl?: string;
  detailUrl: string;
  rawEntryHtml: string;
  lastAcquired: string;
  productId?: string;
  vendorId?: string;
}
